{% set name = "meteomatics" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed5556fefabee166211472e0cf6a27a21bfd7753ab4a0e7d9c500967fecd4ecf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - isodate
    - pandas
    - pathlib2
    - python
    - pytz
    - requests

test:
  requires:
    - pip
  imports:
    - meteomatics
  commands:
    - pip check

about:
  home: https://github.com/meteomatics/python-connector-api
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Meteomatics API connector
  description: Meteomatics API connector
  dev_url: https://github.com/meteomatics/python-connector-api
  doc_url: https://github.com/meteomatics/python-connector-api#readme

extra:
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/109074
  recipe-maintainers:
    - anaconda-services
